### ISSUE TITLE
Download Links in Readme are Dead

### ISSUE THREAD

**Issue by alexanderkiel** [hhund/medicats#1]
Tested 2018 and 2017 and all links were dead.

**Comment by hhund** [comment]
DIMDI recently updated the homepage and change all the download URLs. Unfortunately they also changed the content of the ZIP files. It will take some effort to rewrite the import mechanism.

**Comment by hhund** [comment]
Just fixed the download URLs and pushed a new version that works with the new ZIP files from DIMDI.
